spring:
  main:
    banner-mode: "off"
  application:
    name: sensors
  kafka:
    consumer:
      group-id: sensors
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
    template:
      default-topic: measurments
server:
  contextPath: /api/v1
