spring:
  main:
    banner-mode: "off"
  application:
    name: aggregator
  kafka:
    consumer:
      group-id: aggregator
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
topic:
  income: measurments
  outcome: over_heated
heatLimit: 95.0